backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'authors'
    label: 'Authors'
    folder: 'content/authors'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
  - name: 'recipes'
    label: 'Recipes'
    folder: 'content/recipes'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Meal', name: 'meal', widget: 'select', options: ['Breakfast', 'Lunch', 'Dinner', 'Snack'] }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [], allow_add: true }
      - { label: 'Time', name: 'time', widget: 'number'}
      - { label: 'Rating', name: 'rating', widget: 'number', min: 0, max: 5 }
      - { label: 'Order', name: 'order', widget: 'number' }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        default: "## Ingredients\n- Sugar snap peas, trimmed and diagonally cut\n- 1lb brussels sprouts, shaved\n- Goat or feta cheese crumbles\n- Salt to taste\n- 1 tbsp olive oil\n- 1 tbsp sesame seeds\n## Instructions\n- Steam the peas and sprouts until they're bright green and tender, blanche\n- Place the veggies in a bowl with the rest of the ingredients and mix"